class Factory {
  /**
  {
    "pos":{
      "x":0,
      "y":0,
      "w":0,
      "h":0
    },
    "img":"url",
    "motion":[
      {
        "name":"stand",
        "loop":false,
        "frame":[
          {
            "uv":{
              "ux":0,
              "uy":0,
              "uw":0,
              "uh":0
            },
            "tick":300
          },
          {
            "uv":{
              "ux":0,
              "uy":0,
              "uw":0,
              "uh":0
            },
            "tick":300
          }...
        ]
      },...
    ]
  }
  */
  static createSpirite(json) {

  }
}
